//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGustosa.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderComposition = new HashSet<OrderComposition>();
        }
    
        public int Number { get; set; }
        public int TableId { get; set; }
        public System.DateTime OrderOpenings { get; set; }
        public Nullable<System.DateTime> OrderClosure { get; set; }
        public int KitchenStatusId { get; set; }
        public Nullable<int> UserId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual KitchenStatus KitchenStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderComposition> OrderComposition { get; set; }
        public virtual Tables Tables { get; set; }
        public virtual User User { get; set; }
    }
}
